version: '3.7'

services:     
  mariadb:
    container_name: web-mariadb-4
    hostname: mariadb
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: 4_webappdb
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "0.0.0.0:5024:3306"
      
  web:
    container_name: web-app-calculator-4
    hostname: app
    build: 4_Calculate/
    ports:
      - "0.0.0.0:5004:5004"
